### ISSUE TITLE
Simple Coal Generator Functionality

### ISSUE THREAD

**Issue by Arekenaten** [FWINGBOIZ/Orbit#7]
We need a simple generator to power some introductory machines.

### Acceptance: 
- A generator that takes in burnables and converts to FE energy.
- Should integrate with Forge Energy
- Extends the GUI to show the amount of FE in the machine

### Depends on:
Texture - #4
GUI - #5 
Block + Item - #6

**Comment by Saiyan-Pride23** [comment]
whot
