### ISSUE TITLE
Simple Coal Generator Tests

### ISSUE THREAD

**Issue by Arekenaten** [FWINGBOIZ/Orbit#8]
We need tests for the simple generator.

### Acceptance:
- Tests?

**Comment by Arekenaten** [comment]
So I looked into this today and it seems that it's just basically impossible to write tests for Mods unless you are testing the mod-specific functionality. Apparently the MC classes just suck.

**Comment by gchagan36** [comment]
Big oof, should we close this issue then?

**Comment by Arekenaten** [comment]
I think so. We can revisit this if needed or if we find some examples of tests that we can follow. There's practically nothing out there for this.
